--CAU 3

CONN BTVN_1/btvn1;

GRANT CREATE SESSION TO R_TRUONG_PHONG;
GRANT INSERT, UPDATE ON DU_AN TO R_TRUONG_PHONG;
GRANT SELECT ON DU_AN TO R_TRUONG_PHONG;
GRANT R_TRUONG_PHONG TO NV025, NV009, NV020, NV017, NV024;

